csv-site/config/routes.rb
Rails.application.routes.draw do

  get 'sent_mail/retry_password_to_email'

=begin
  resources :clients, path: :form, only: [] do
    get 'entry', to: :new
    post  'entry', to: :create
  end
=end

=begin
  resources :clients, path: :account, except: [] do
    get '', to: :show_account
  end
=end

  resources :active_reports
  resources :images

  resources :clients
  resources :employees

=begin
  get 'employee/find', to: 'employees#find'
  get 'employees/find_result'
=end

  root :to => 'start_page#start_page'

  resource :admin_user_login, path: :admin, only: [] do
    get  'login',  to: :new
    post 'login',  to: :create
    get  'logout', to: :destroy
  end

  resource :client_user_login, path: :user, only: [] do
    get  'login',  to: :new
    post 'login',  to: :create
    get  'logout', to: :destroy
    get  'reset_password/:id', to: :reset_password, as: 'reset_password'
    patch 'reset_password/:id', to: :reset_password_set
  end

  get "sent_mail/retry_password_to_email" , to: 'sent_mail#retry_password_to_email', as: 'retry_password'
  post "sent_mail/retry_password_to_email" , to: 'sent_mail#retry_password_to_email_post'

=begin
  resource :session, path: :admin, only: [] do
    get 'login', to: :new
    post 'login', to: :create
    get 'logout', to: :destroy
  end
=end

end

csv-site/app/models/active_report.rb
class ActiveReport < ActiveRecord::Base

  
  scope :available, -> {
    where('publish_start_date <= ? OR publish_start_date IS NULL', Date.today)
      .where('publish_end_date >= ? OR publish_end_date IS NULL', Date.today)
  }  

  belongs_to :category
  belongs_to :client_user
  belongs_to :client
  #nnテーブル設定(image)
  has_many :images_active_report
  has_many :images, through: :images_active_report

  #nnテーブル設定(tag)
  has_many :active_reports_tag
  has_many :tags, through: :active_reports_tag
  
  #has_and_belongs_to_many :tags 

end

csv-site/app/models/active_reports_tag.rb
class ActiveReportsTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :active_report
end

csv-site/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  #admin_userのパスワード検証
  #メソッド全体でtrue or false を返す
  def correct_password?(input_password)
    self.password == input_password
  end


  #入力したパスワードをハッシュ化
=begin
  def hashed_password(nomal_password)
    Digest::MD5.hexdigest(nomal_password).to_s
  end
=end

end

csv-site/app/models/category.rb
class Category < ActiveRecord::Base

end

csv-site/app/models/client.rb
class Client < ActiveRecord::Base
  
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :donation_purpose
  belongs_to :donation_pay_method
  belongs_to :contract_status
  belongs_to :prefectures_name

  has_many :employees
  has_many :active_reports

end

csv-site/app/models/client_of_shop.rb
class ClientOfShop < ActiveRecord::Base
end

csv-site/app/models/client_user.rb
class ClientUser < ActiveRecord::Base

  #1:nテーブルの設定
  has_many :donations
    
    #メソッド全体でture or falseを返す
    def correct_password?(input_password)
      #引数として持ってきたsessionに格納されたパスワードと、 sessionのemailで検索されたユーザが持っているパスワードを比較して検証
      self.password  ==  input_password #入力されたパスワードの文字列をハッシュ化して検証 →検証のやり方はあっているのか？
      #input_passwordはもともと文字列で入ってきている
      #インスタンスメソッド(self.)の利用でuserもこっちへ持って来れる
      #パスワードはMD5化したもので、password_digeに保存 
    end

=begin
    def self.hashed_password(unique_password) #self.を入れないとnomethod error が返る
        Digest::MD5.hexdigest(unique_password).to_s
    end
=end

end

csv-site/app/models/contract_status.rb
class ContractStatus < ActiveRecord::Base
end

csv-site/app/models/donation.rb
class Donation < ActiveRecord::Base

#1:nテーブルの設定
belongs_to :receipt_of_money_status
belongs_to :client_user


=begin 
  class ClientSearch(client)
  scope :client_donations, -> {
    where('client_id == ? ', Donation.find_by(id: client.id) )
  }
  end
=end
end

csv-site/app/models/donation_purpose.rb
class DonationPurpose < ActiveRecord::Base

end

csv-site/app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :client
  belongs_to :sex
end

csv-site/app/models/image.rb
class Image < ActiveRecord::Base
  has_many :images_active_report
  has_many :active_reports, through: :images_active_report
end

csv-site/app/models/prefectures_name.rb
class PrefecturesName < ActiveRecord::Base
end

csv-site/app/models/sex.rb
class Sex < ActiveRecord::Base
  has_many :employees
end

csv-site/app/models/supporter_voice.rb
class SupporterVoice < ActiveRecord::Base

end

csv-site/app/models/tag.rb
class Tag < ActiveRecord::Base
  #nnテーブル設定(tag)
  has_many :active_reports_tag
  has_many :active_reports, through: :active_reports_tag
end

csv-site/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  #before_action or before_filterはapplication_controllerに記載すべきか？ その場合、実行するコントローラー(class名の指定はどうするのか？)  
  before_action :require_client_user_login!, except: [:index, :show]
  before_action :require_client_user_login!, only: [:destroy]


  before_filter  :loging_client_user, only: [:edit, :destroy]


  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
  
    @client.save
    render :text => 'success'
  end
  
  def show
    @client = Client.find(params[:id])
    @client_donations = Donation.where(client_id: @client.id) #引っかかるものをすべて出す
  end

  def index
    @clients = Client.all
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    @client.update_attributes(client_params)
    redirect_to client_path
  end



  private
    def client_params
      params.require(:client).permit(:name, :address, :tel_number, 
                                   :client_email, :client_president, :client_manager, :client_description, 
                                   :price_per_employee, :contract_status_id, :donation_purpose_id, 
                                   :donation_pay_method_id, :prefectures_name_id ) 
    end
end

csv-site/app/helpers/clients_helper.rb
module ClientsHelper
end

csv-site/app/helpers/employees_helper.rb
module EmployeesHelper
end

csv-site/app/helpers/images_helper.rb
module ImagesHelper
end

csv-site/app/helpers/sent_mail_helper.rb
module SentMailHelper
end

csv-site/app/helpers/sessions_helper.rb
module SessionsHelper
end

csv-site/app/helpers/start_page_helper.rb
module StartPageHelper
end

csv-site/app/views/clients/_client_all.html.erb
<% @clients.each do |client| %>
<table border ='1'>
  <tr>
    <td>会社名:</td> <td><%= client.name %></td>
  </tr>
  <tr>
    <td>住所:</td> <td><%= client.address %></td>
  </tr>
  <tr>
    <td>電話番号:</td> <td><%= client.tel_number%></td>
  </tr>
  <tr>
    <td>メールアドレス:</td>  <td><%= client.client_email %></td>
  </tr>
  <tr>
    <td>代表者名:</td> <td><%= client.client_president %></td>
  </tr>
  <tr>
    <td>担当者名:</td> <td><%= client.client_manager %></td>
  </tr>
  <tr>
    <td>会社概要:</td> <td><%= client.client_description %></td>
  </tr>
  <tr>
    <td>寄付目的:</td> <td><%= client.donation_purpose.donation_purpose %></td>
  </tr>
  <tr>
    <td>契約状況:</td> <td><%= client.contract_status.contract_status %></td>
  </tr>
  <tr>
    <td>支払い方法:</td> <td><%= client.donation_pay_method.donation_pay_method %></td>
  </tr>
  <tr>
    <td>基本寄付金額:</td> <td><%= client.price_per_employee %></td>
  </tr>
  <tr>
    <td><%= link_to '詳細', client_path(client.id) %></td>
    <td><%= link_to '編集', edit_client_path(client.id) %></td>
  </tr>
</table>

<p>  </p>
<% end -%>

csv-site/app/views/clients/_client_data.html.erb
<h2>会社情報</h2>
<table border = '1'>
  <tr>    
    <td>会社名:  <%= @client.name %></td>
  </tr>
  <tr>
    <td>住所:  <%= @client.address %></td> 
  </tr>
  <tr> 
    <td>電話番号:  <%= @client.tel_number %></td>
  </tr>
  <tr>
    <td>メールアドレス:  <%= @client.client_email %></td>
  </tr>
  <tr>
    <td>代表者名:  <%= @client.client_president %></td>
  </tr>
  <tr>
    <td>担当者名:  <%= @client.client_manager %></td>
  </tr>
  <tr>  
    <td>会社概要:  <%= @client.client_description %></td>
  </tr>
  <tr>
    <td>寄付目的:  <%= @client.donation_purpose.donation_purpose %></td>
  </tr>
    <td>支払い方法:  <%= @client.donation_pay_method.donation_pay_method %></td>
  <tr>
    <td>契約状況:  <%= @client.contract_status.contract_status %></td>
  </tr>
</table>

csv-site/app/views/clients/_client_donations.html.erb
<h2>寄付情報</h2>


寄付回数: <%= @client_donations.count %> <br />

  <% @client_donations.each do |donation| %>
    <table border = '1'>
      <tr>
        <td>寄付メッセージ:</td><td><%= donation.try(:donation_message) %></td>
      </tr>
      <tr>
        <td>寄付担当者:</td><td><%= donation.client_user.try(:name) %></td>
      </tr>
      <tr>
        <td>寄付金額:</td><td><%= donation.try(:donation_total_amount) %></td>
      </tr>
      <tr>
        <td>支払い状況:</td><td><%= donation.receipt_of_money_status.try(:receipt_of_money_status) %></td>
      </tr>
    </table>
    <p> </p>
  <% end -%>

<!-- ここには、donationページが個別でできた場合のリンク
      <tr>
        <td><%= link_to '寄付詳細', client_path %></td>
        <td><%= link_to '寄付情報編集', edit_client_path %></td>
      </tr>
-->

csv-site/app/views/clients/_client_employee.html.erb
<h2>メンバー情報</h2>

総メンバー数: <%= @client.employees.count %> <br />

  <% @client.employees.each do |employee| %>
    <table border = '1'>
      <tr>
        <td>従業員名:</td><td><%= employee.try(:name) %></td>
      </tr>
      <tr>
        <td>メールアドレス:</td><td><%= employee.try(:employee_email) %></td>
      </tr>
      <tr>
        <td>寄付金額:</td><td><%= employee.try(:donation_price) %></td>
      </tr>
      <tr>
        <td><%= link_to '詳細', employee_path(employee.id) %></td>
        <td><%= link_to '編集', edit_employee_path(employee.id) %></td>
      </tr>
    </table>
    <p> </p>
  <% end -%>

csv-site/app/views/clients/_form.html.erb
<%= form_for @client do |f| %>
  
  <table>
  
  <tr>
  <td><%= f.label '寄付目的' %></td>
  <td><%= f.collection_select :donation_purpose_id, DonationPurpose.all, :id, :donation_purpose %></td>
  </tr>

  <tr>
  <td><%= f.label '支払い方法' %></td>
  <td><%= f.collection_select :donation_pay_method_id, DonationPayMethod.all, :id, :donation_pay_method %></td>
  </tr>

  <tr>
  <td><%= f.label '一人当たりの寄付金額' %></td>
  <td><%= f.text_field :price_per_employee %></td>
  </tr>
  
  <tr>
  <td><%= f.label '契約状況' %></td>
  <td><%= f.collection_select :contract_status_id, ContractStatus.all, :id, :contract_status %></td>
  </tr>

  <tr>
  <td><%= f.label  '会社名'  %></td>
  <td><%= f.text_field :name %></td>
  </tr>

  <tr>
  <td><%= f.label '所在地'  %></td>
  <td><%= f.collection_select :prefectures_name_id, PrefecturesName.all, :id, :prefectures_name %></td>
  </tr>

  <tr>
  <td><%= f.label '市区町村'  %></td>
  <td><%= f.text_field :address %></td>
  </tr>

  <tr>
  <td><%= f.label '電話番号'  %></td>
  <td><%= f.telephone_field :tel_number %></td>
  </tr>

  <tr>
  <td><%= f.label 'メールアドレス' %></td>
  <td><%= f.text_field :client_email %></td>
  </tr>

  <tr>
  <td><%= f.label '代表者名'  %></td>
  <td><%= f.text_field :client_president %></td>
  </tr>

  <tr>
  <td><%= f.label '担当者名'  %></td>
  <td><%= f.text_field :client_manager %></td>
  </tr>

  <tr>
  <td><%= f.label '会社概要'  %></td>
  <td><%= f.text_area :client_description %></td>
  </tr>

  <tr>
  <td><%= f.submit "登録" %></td>
  </tr>

  </table>

<% end -%>

csv-site/app/views/clients/_search_employee.html.erb
<h3>従業員検索</h3>
<%= form_for @search_form, :url => clients_path do |f| %>
  <%= f.search_field :q %>
  <%= f.submit '検索' %>
<% end %>

csv-site/app/views/clients/edit.html.erb
<h2>編集画面</h2>

<%= render 'form' %>

csv-site/app/views/clients/index.html.erb
<h1>会社一覧</h1>

<%= render 'client_all' %>

csv-site/app/views/clients/new.html.erb
<h1>新規登録</h1>

<%= render 'form' %>

csv-site/app/views/clients/show.html.erb
<h1>会社基本情報</h1>
<%= render 'client_data' %>
<%= link_to '編集', edit_client_path %>


<%= render 'client_employee' %>

<%= render 'client_donations' %>