csv-site/config/routes.rb
Rails.application.routes.draw do

  get 'sent_mail/retry_password_to_email'

=begin
  resources :clients, path: :form, only: [] do
    get 'entry', to: :new
    post  'entry', to: :create
  end
=end

=begin
  resources :clients, path: :account, except: [] do
    get '', to: :show_account
  end
=end

  resources :active_reports
  resources :images

  resources :clients
  resources :employees

=begin
  get 'employee/find', to: 'employees#find'
  get 'employees/find_result'
=end

  root :to => 'start_page#start_page'

  resource :admin_user_login, path: :admin, only: [] do
    get  'login',  to: :new
    post 'login',  to: :create
    get  'logout', to: :destroy
  end

  resource :client_user_login, path: :user, only: [] do
    get  'login',  to: :new
    post 'login',  to: :create
    get  'logout', to: :destroy
    get  'reset_password/:id', to: :reset_password, as: 'reset_password'
    patch 'reset_password/:id', to: :reset_password_set
  end

  get "sent_mail/retry_password_to_email" , to: 'sent_mail#retry_password_to_email', as: 'retry_password'
  post "sent_mail/retry_password_to_email" , to: 'sent_mail#retry_password_to_email_post'

=begin
  resource :session, path: :admin, only: [] do
    get 'login', to: :new
    post 'login', to: :create
    get 'logout', to: :destroy
  end
=end

end

csv-site/app/models/active_report.rb
class ActiveReport < ActiveRecord::Base

  
  scope :available, -> {
    where('publish_start_date <= ? OR publish_start_date IS NULL', Date.today)
      .where('publish_end_date >= ? OR publish_end_date IS NULL', Date.today)
  }  

  belongs_to :category
  belongs_to :client_user
  belongs_to :client
  #nnテーブル設定(image)
  has_many :images_active_report
  has_many :images, through: :images_active_report

  #nnテーブル設定(tag)
  has_many :active_reports_tag
  has_many :tags, through: :active_reports_tag
  
  #has_and_belongs_to_many :tags 

end

csv-site/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  #admin_userのパスワード検証
  #メソッド全体でtrue or false を返す
  def correct_password?(input_password)
    self.password == input_password
  end


  #入力したパスワードをハッシュ化
=begin
  def hashed_password(nomal_password)
    Digest::MD5.hexdigest(nomal_password).to_s
  end
=end

end

csv-site/app/models/category.rb
class Category < ActiveRecord::Base

end

csv-site/app/models/client.rb
class Client < ActiveRecord::Base
  
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :donation_purpose
  belongs_to :donation_pay_method
  belongs_to :contract_status
  belongs_to :prefectures_name

  has_many :employees
  has_many :active_reports

end

csv-site/app/models/client_of_shop.rb
class ClientOfShop < ActiveRecord::Base
end

csv-site/app/models/client_user.rb
class ClientUser < ActiveRecord::Base

  #1:nテーブルの設定
  has_many :donations
    
    #メソッド全体でture or falseを返す
    def correct_password?(input_password)
      #引数として持ってきたsessionに格納されたパスワードと、 sessionのemailで検索されたユーザが持っているパスワードを比較して検証
      self.password  ==  input_password #入力されたパスワードの文字列をハッシュ化して検証 →検証のやり方はあっているのか？
      #input_passwordはもともと文字列で入ってきている
      #インスタンスメソッド(self.)の利用でuserもこっちへ持って来れる
      #パスワードはMD5化したもので、password_digeに保存 
    end

=begin
    def self.hashed_password(unique_password) #self.を入れないとnomethod error が返る
        Digest::MD5.hexdigest(unique_password).to_s
    end
=end

end

csv-site/app/models/contract_status.rb
class ContractStatus < ActiveRecord::Base
end

csv-site/app/models/donation.rb
class Donation < ActiveRecord::Base

#1:nテーブルの設定
belongs_to :receipt_of_money_status
belongs_to :client_user


=begin 
  class ClientSearch(client)
  scope :client_donations, -> {
    where('client_id == ? ', Donation.find_by(id: client.id) )
  }
  end
=end
end

csv-site/app/models/donation_purpose.rb
class DonationPurpose < ActiveRecord::Base

end

csv-site/app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :client
  belongs_to :sex
end

csv-site/app/models/image.rb
class Image < ActiveRecord::Base
  has_many :images_active_report
  has_many :active_reports, through: :images_active_report
end

csv-site/app/models/prefectures_name.rb
class PrefecturesName < ActiveRecord::Base
end

csv-site/app/models/sex.rb
class Sex < ActiveRecord::Base
  has_many :employees
end

csv-site/app/models/supporter_voice.rb
class SupporterVoice < ActiveRecord::Base

end

csv-site/app/models/tag.rb
class Tag < ActiveRecord::Base
  #nnテーブル設定(tag)
  has_many :active_reports_tag
  has_many :active_reports, through: :active_reports_tag
end

csv-site/app/controllers/start_page_controller.rb
class StartPageController < ApplicationController
  def start_page
  end

  def about
  end
 
  def help
  end

end

csv-site/app/helpers/clients_helper.rb
module ClientsHelper
end

csv-site/app/helpers/employees_helper.rb
module EmployeesHelper
end

csv-site/app/helpers/images_helper.rb
module ImagesHelper
end

csv-site/app/helpers/sent_mail_helper.rb
module SentMailHelper
end

csv-site/app/helpers/sessions_helper.rb
module SessionsHelper
end

csv-site/app/helpers/start_page_helper.rb
module StartPageHelper
end

csv-site/app/views/start_page/about.html.erb
<h1>about</h1>


<p>ここが、概要です！</p>

csv-site/app/views/start_page/help.html.erb
<h1>Help</h1>

<p>ここが、helpページです！</p>

csv-site/app/views/start_page/start_page.html.erb
<h1>csv-site</h1>

<%= link_to '協力企業一覧', clients_path %>  <br />

<%= link_to '参加メンバー一覧', employees_path %>  <br />

<%= link_to '記事一覧', active_reports_path %> <br />

<%= link_to 'クライアントログイン', login_client_user_login_path %>  <br />

<%= link_to '管理者ログイン', login_admin_user_login_path %>  <br />


<% if session[:client_user_id].present?  %>

  <h3>User Status</h3>
  <% @client_user =  ClientUser.find(session[:client_user_id])  %> 
  name: <%= @client_user.name %> <br />
  email: <%= @client_user.email %> <br />

  <% if @client_user.client_id.present?  %>
    <%= link_to '所属企業詳細', client_path(@client_user.client_id) %>
  <% end -%>
  
  <%= link_to 'ユーザー情報編集' %>
  <%= link_to 'ログアウト', :controller => "client_user_logins", :action => "destroy",  data: {:confirm => "本当にログアウトしますか？"} %>

<% end -%>

<% if session[:admin_user_id].present?  %>

<h3>Admin user status</h3>
<% @admin_user =  AdminUser.find(session[:admin_user_id])  %> 
name: <%= @admin_user.name %> <br />
email: <%= @admin_user.email %> <br />


  <%= link_to 'ユーザー情報編集' %>
  <%= link_to 'ログアウト', :controller => "admin_user_logins", :action => "destroy",  data: {:confirm => "本当にログアウトしますか？"} %>
<% end -%>